### ISSUE TITLE
cant import save

### ISSUE THREAD

**Issue by Dragorise2** [Exiua/LTSaveEd#12]
hi, I have this issue where I can't import the saves from my game e.g when I open the .exe and click on open>import nothing pops up. any advice?

**Comment by Exiua** [comment]
Which version of Windows are you running? Also you can try the .jar and see if that works for you (if you haven't already)

**Comment by Dragorise2** [comment]
Edition	Windows 10 Home
Version	21H2
Installed on	‎5/‎1/‎2023
OS build	19044.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

tried using .jar as well same thing click on open>import nothing pops up

**Comment by Exiua** [comment]
I've [updated](https://github.com/Exiua/LTSaveEd/releases/tag/v1.4.1) the editor so it should work for you know. Let me know if you are still running into this issue.
