### ISSUE TITLE
Can't launch editor.

### ISSUE THREAD

**Issue by Agusik** [Exiua/LTSaveEd#13]
Java Virtual Machine Launcher error "A Java Exception has occurred." The latest version of Java is installed.

**Comment by Exiua** [comment]
What is the exact version of Java you have installed? You can check this by running `java --version` in a terminal.

**Comment by Agusik** [comment]
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)

**Comment by Exiua** [comment]
It seems you have the latest version of Java 8 installed. You will need Java 14 or higher to use the save editor (you can download Java 20 from here: [https://www.oracle.com/java/technologies/downloads/](https://www.oracle.com/java/technologies/downloads/)). 

Once you have download a compatible Java version, you can run `java --version` to see if the java command auto updated to the new version. If the java command now points to the compatible version of java, you should be able to double-click the jar file to run it, or you can use `java -jar LTSaveEd.jar` to run the jar file. If the java command still points to Java 8, you will need to find the java executable file and use it to run the jar file (the command will look something like this on Windows: `C:/path/to/java14+_jdk/bin/java.exe -jar LTSaveEd.jar`)

**Comment by Agusik** [comment]
Now it works, thanks. What led me into this situation was that when the launch attempt crashed, the Java 8 download page opened.
