### ISSUE TITLE
Don't know where to run from and have found no answers. Also doesn't open.

### ISSUE THREAD

**Issue by Leviathan887** [Exiua/LTSaveEd#15]
For the Jar, where should I run it from for good results? Should I run it as a standalone .jar file, run it from somewhere inside LT, or run it from the LTSaveEd.zip folder?
I am asking because there are no clear answers from the description and README which just say to run it.
I'm also putting this as an issue because I don't know how else to ask.

**Comment by Leviathan887** [comment]
J

**Comment by Leviathan887** [comment]
Accidentally closed the issue, sorry. Also, it says that it cannot be opened when run as standalone. I also tested within LT and it said the same thing. I also tried running it in the terminal with both the instructed way and dragging into the terminal and it said "zsh: permission denied"
MacOS btw

**Comment by Exiua** [comment]
You should only need the .jar file to run the save editor. Also make sure you have Java 14 or greater (you can check this by running `java --version` or using the full path to the java executable for Java 14+).

If the above does not work, you could try downloading the source code and compiling it manually (you will need to have JavaFx 16 or greater installed). Unfortunately, I have only been able to test the save editor on Windows and Linux.

**Comment by Leviathan887** [comment]
I have been doing some research and checked privileges for the file. It turns out that I didn't have execute privileges for the jar. I gave myself these privileges and tried again but this time when run in terminal, it outputs "zsh: exec format error". I have been unable to find clear answers as to what this means. Also, what's the difference between JavaFx and java? I only have installed java.

**Comment by Exiua** [comment]
JavaFx is the Java library I am using to build/control the GUI. As of Java 11, it is no longer bundled with Java, so you will need to download it separately if you would like to compile and run the source code. 

The published .jar file for the save editor should already have JavaFx bundled in it for Windows, Mac, and Linux (I have tested this on Windows and Linux), so you should be able to run the .jar file without having to download JavaFx yourself.

Also how exactly are you trying to run the .jar file? When I tested in Linux (Ubuntu), I wasn't able to run the save editor with `./LTSaveEd.jar`, but `java -jar ./LTSaveEd.jar` worked. If that doesn't work, you can try using the full path for Java14+ (e.g., something like `/Library/Java/JavaVirtualMachines/jdk14.0.2.jdk/Contents/Home/bin/java -jar ./LTSaveEd.jar`). I am not too sure by how much Linux differs from MacOS.
