### ISSUE TITLE
Hate to bother, but I cannot get it to run. 

### ISSUE THREAD

**Issue by ImHoppingMad** [Exiua/LTSaveEd#16]
Rather confused on how to get this to run at all, It just errors out. if I use the .jar 
![image](https://github.com/Exiua/LTSaveEd/assets/87835029/35abc00c-861b-4412-9a9e-6046759fea54)
or if I try to use the EXE it says I don't have java installed (which I do and have the latest version of.) 
![image](https://github.com/Exiua/LTSaveEd/assets/87835029/1ef3e07a-2214-4c9d-8d66-b32a5c41453d)
so.. I'm totally stumped.

**Comment by Exiua** [comment]
What is the output you get when you run `java --version` in a terminal?

**Comment by ImHoppingMad** [comment]
![image](https://github.com/Exiua/LTSaveEd/assets/87835029/93f17e12-a83e-4f7c-955a-814ecacad8d5)
it does this.

**Comment by Exiua** [comment]
Try `java -version` (though I suspect you have Java 8 or earlier installed atm). You can download Java 20 from here: [https://www.oracle.com/java/technologies/downloads/#jdk20-windows](https://www.oracle.com/java/technologies/downloads/#jdk20-windows). The save editor works with Java 19 or newer, so Java 20 should work.

**Comment by ImHoppingMad** [comment]
![image](https://github.com/Exiua/LTSaveEd/assets/87835029/42bc25ed-f870-40f8-9666-01c2096d08d9)
it says 1.8.0

**Comment by Exiua** [comment]
Java 1.8.0 is Java 8, so you will need to install Java 20.

**Comment by ImHoppingMad** [comment]
> Java 1.8.0 is Java 8, so you will need to install Java 20.

It worked! Thank you so much for being patient and helping me out, I appreciate it greatly, have a good one!

**Comment by Exiua** [comment]
No problem, I'm glad I was able to help!
