### ISSUE TITLE
[BUG] Attribute editing window doesnt work.

### ISSUE THREAD

**Issue by ShabalinGit** [Exiua/LTSaveEd#36]
![Снимок экрана_20-8-2024_204117_exiua github io](https://github.com/user-attachments/assets/34a17ac8-de4a-4a8f-9a5f-cca676dd5895)
Upon loading the save and opening attribute menu, LTSaveEd sais "An unhandled error has occurred. [Reload]" at the bottom and attribute window in empty. Other things(care, perks ext.) are working normal.

Just opening attributes window after loading the save.

**Additional Information (please complete the following information):**
Tryed starting a new game to get new save.

**Comment by Exiua** [comment]
I was unable to reproduce the issue you are encountering. Could you send me a copy of the save file where this issue occurs? Also, what version of Lilith's Throne is the save from (the latest version of the game that I have tested with is v0.4.9.9)?
