### ISSUE TITLE
Need help compiling

### ISSUE THREAD

**Issue by s-inactive** [Exiua/LTSaveEd#37]
I'm not sure what I'm doing wrong.  Can anyone help me compile this?

**Comment by Exiua** [comment]
What have you done so far when you have tried compiling the project? Also, what environment (e.g., IDE) are you using to compile the project?

**Comment by s-inactive** [comment]
I was trying this with visual studio.  While not completely, I am a complete beginner.  The compiling process starts out fine before showing a whole slew of errors.
Someone mentioned the "dotnet run" command, which is what I'm using now.

**Comment by s-inactive** [comment]
Do I need an extra component or something?

**Comment by Exiua** [comment]
No, if the program runs fine when you use `dotnet run`, you have everything you need to build the solution.

When you run the program, in the build output terminal, you should see a line that says `Now listening on: http://localhost:5139` (the port may be different). You can visit that url (`http://localhost:5139` in my example) to view the running save editor.

**Comment by Exiua** [comment]
Out of curiosity, why are you compiling the save editor?

**Comment by s-inactive** [comment]
> When you run the program, in the build output terminal, you should see a line that says `Now listening on: http://localhost:5139` (the port may be different). You can visit that url (`http://localhost:5139` in my example) to view the running save editor.

This is working.  It's what I'm using now.

> Out of curiosity, why are you compiling the save editor?

Just a personal preference.  I prefer it on my pc because of all the hoops I have to go through to allow an app through my firewall.

This can be marked as solved since I got what I needed even though compiling still gives me problems.  Maybe its a skill issue.

**Comment by Exiua** [comment]
Sounds good, if you are still getting issues when compiling, you could open a new issue with a log of those warnings/errors, and I can check to see if there is something I can fix in the program to resolve those issues.
