### ISSUE TITLE
problems with resolution

### ISSUE THREAD

**Issue by HoverLass** [Exiua/LTSaveEd#4]
the program is not compatible with all screen resolution 
for example my screen resolution is 1920 x 1080
this conflicts with the programs window resolution as it cut off near the bottom area, which prevent access to the features laid down there and with there being no scroll bar it is impossible to access it.

**Comment by Exiua** [comment]
Which tabs does this occur under? Also, could you provide screenshots of the issue?

**Comment by HoverLass** [comment]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/115282443/195994963-1b00d44e-a20c-42d7-be30-69aa7d08c243.png">

it seems to happen to the core tab i cant seem to access mana section or the delete character button

**Comment by Exiua** [comment]
This should now be fixed in the latest release.

**Comment by HoverLass** [comment]
thank you very much, very appreciated
